### ISSUE TITLE
Add the need to change line 61 in the "Configure the Application" in the README

### ISSUE THREAD

**Issue by joanma747** [securedimensions/STAplus-SCK-App#2]
Two different people came to me with the same problem:

![image](https://github.com/securedimensions/STAplus-SCK-App/assets/5230444/8a7f7350-6b8f-4c47-98aa-054ad589e93a)

This is because they did not understood that what the README says in the "Connect the Hardware" has implications in the Python code. 

So please add in the end of the seccion Configure the Application the following:

"
The file SensorApp.py contains the line 61 the variable representing the serial port. Please update as you see fit (considering what is explained in the "Connect the Hardware" of this README)!

`sck = Serial('/dev/tty.usbmodem14301', 115200, timeout=10)
`
"

Thanks,

**Comment by securedimensions** [comment]
README updated
